"""End-to-end: a synthetic study through every lifecycle verb, gate by gate.

This is the executable form of docs/first-study.md. If it passes, a new user
can follow the document and arrive at the same place.
"""

import csv
import json
import shutil
import subprocess
from pathlib import Path

import pytest

import numpy as np

from studies import cli, gates, llm

STUDY = "walk-001"


@pytest.fixture
def workspace(tmp_path, monkeypatch):
    """A throwaway repo with a studies/ directory, git-initialized so the guards run."""
    repo = tmp_path / "repo"
    (repo / "studies").mkdir(parents=True)
    monkeypatch.setenv("YARDSTICK_STUDIES_ROOT", str(repo / "studies"))
    if shutil.which("git"):
        subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
        subprocess.run(["git", "config", "user.email", "t@t"], cwd=repo, check=True)
        subprocess.run(["git", "config", "user.name", "t"], cwd=repo, check=True)
    return repo


def _raw_csv(path: Path, n: int = 40) -> None:
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["OBSID", "speaker", "text"])
        w.writeheader()
        for i in range(n):
            for k in range(3):
                w.writerow({"OBSID": f"t{i:03d}", "speaker": "student", "text": f"utterance {k} of {i}"})


def _per_unit(path: Path, conditions, dims, n=60, seed=0, shift=None):
    rng = np.random.default_rng(seed)
    shift = shift or {}
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["unit_id", "condition", "dimension", "f_treatment", "f_reference"])
        w.writeheader()
        for i in range(n):
            for cond in conditions:
                for dim in dims:
                    ref = rng.normal(1.0, 0.3)
                    d = rng.normal(shift.get((cond, dim), 0.0), 0.05)
                    w.writerow({"unit_id": f"u{i:03d}", "condition": cond, "dimension": dim, "f_treatment": f"{ref + d:.6f}", "f_reference": f"{ref:.6f}"})


def _gate(repo, study, gate_id):
    status = gates.study_status(repo, repo / "studies" / study)
    return next(g for g in status["gates"] if g["gate"] == gate_id), status


def test_lifecycle(workspace, capsys):
    repo = workspace
    root = repo / "studies" / STUDY

    # G0: init from a template + terms + split ------------------------------
    assert cli.main(["init", STUDY, "--title", "Walkthrough", "--llm", "--template", "paired-equivalence"]) == 0
    (root / "acquisition" / "access-terms.md").write_text(
        "# walk-001 — data access terms\n\nDataset: synthetic rows generated by the walkthrough.\n"
        "License: none (synthetic). Terms: research use only; not shared.\n"
        "File hashes: rows.csv recorded in registration/facts.md after the split.\n"
        "Scope: transcript text and speaker labels only.\n"
    )
    raw = root / "data" / "rows.csv"
    _raw_csv(raw)
    assert cli.main(["split", STUDY, "--csv", str(raw), "--id-column", "OBSID", "--seed", "11"]) == 0
    g0, status = _gate(repo, STUDY, "G0")
    assert g0["ok"], json.dumps(g0, indent=1)
    assert status["current"] == "G1"

    if shutil.which("git"):
        subprocess.run(["git", "add", "."], cwd=repo, check=True)
        tracked = subprocess.run(["git", "ls-files"], cwd=repo, capture_output=True, text=True, check=True).stdout
        assert "rows.csv" not in tracked

    # A script that opens the raw file directly is caught.
    bad = root / "scripts" / "peek.py"
    bad.write_text('open("rows.csv")\n')
    assert cli.main(["check", STUDY]) == 1
    bad.unlink()

    # G1: measures declared with units/direction/kind, validated; exploratory pass on every arm;
    #     generator recorded ----------------------------------------------------
    (root / "config" / "analysis.json").write_text(json.dumps({
        "mode": "equivalence", "alpha": 0.05, "bootstrap_reps": 300, "seed": 1,
        "primary_condition": "calibrated", "conditions": ["calibrated", "uncalibrated"],
        "dimensions": [
            {"name": "length", "units": "log ratio of mean words per utterance", "direction": "higher = longer", "kind": "direct", "delta": 0.05},
            {"name": "questions", "units": "share of utterances", "direction": "higher = more questions", "kind": "classifier", "delta": 0.05},
        ],
    }, indent=2))
    (root / "config" / "measure-validation.json").write_text(json.dumps({
        "floors": {"precision": 0.8, "recall": 0.8},
        "measures": {"questions": {"kind": "classifier", "precision": 0.94, "recall": 0.86, "against": "hand-coded 500 utterances", "n": 500}},
    }, indent=2))
    _per_unit(root / "output" / "per-unit.csv", ["calibrated", "uncalibrated"], ["length", "questions"],
              shift={("uncalibrated", "length"): 0.4, ("uncalibrated", "questions"): 0.3})
    assert cli.main(["analyze", STUDY, "--partition", "exploratory", "--commit-tag", "explore"]) == 0
    gen_cfg = json.loads((root / "config" / "generation.json").read_text())
    gen_cfg.update({"model": "example-model-1", "api_parameters": {"max_tokens": 150, "temperature": 1.0},
                    "model_retirement": "2099-01-01", "cost_cap_usd": 50.0, "conditions": ["calibrated", "uncalibrated"]})
    (root / "config" / "generation.json").write_text(json.dumps(gen_cfg, indent=2))
    request = {"model": "example-model-1", "max_tokens": 150, "temperature": 1.0,
               "system": [{"type": "text", "text": "You are a student."}], "messages": [{"role": "user", "content": "Teacher turn"}]}
    record = llm.generator_record(gen_cfg, "You are a student.", request, generator="anthropic-api")
    llm.write_json(root / "output" / "exploratory-generator.json", record)
    assert cli.main(["facts", STUDY]) == 0
    assert cli.main(["check", STUDY]) == 0
    g1, status = _gate(repo, STUDY, "G1")
    assert g1["ok"], json.dumps(g1, indent=1)
    assert status["current"] == "G2"

    # G2: a freeze with open slots is refused; a validated, piloted draft freezes ----
    assert cli.main(["freeze", STUDY, "--version", "v0.1"]) == 1
    draft = root / "registration" / "osf-registration-draft.md"
    text = draft.read_text()
    for hole in gates.open_placeholders(text):
        text = text.replace(hole, "decided")
    draft.write_text(text)
    assert cli.main(["freeze", STUDY, "--version", "v1.0"]) == 0
    frozen = json.loads((root / "registration" / "protocol-frozen.json").read_text())
    assert frozen["content"]["registration_sha256"] and not frozen["content"]["rehearsal"]
    assert (root / "registration" / "osf-export.md").exists()
    g2, status = _gate(repo, STUDY, "G2")
    assert g2["ok"], json.dumps(g2, indent=1)
    assert status["current"] == "G3"

    # G3: unlock, run on the registered generator with a spend ledger, verify ----
    assert cli.main(["unlock", STUDY, "--reason", "registration frozen: v1.0"]) == 0
    llm.write_json(root / "output" / "confirmatory-generator.json", record)  # same generator: no drift
    ledger = llm.SpendLedger(root / "output" / "spend-ledger.jsonl", {"input": 3.0, "output": 15.0, "cache_read": 0.3, "cache_write": 3.75}, cap_usd=50.0)
    for _ in range(20):
        ledger.record({"input_tokens": 4000, "output_tokens": 150, "cache_read_input_tokens": 3000}, note="turn")
    assert ledger.summary()["within_cap"]
    assert cli.main(["analyze", STUDY, "--partition", "confirmatory", "--commit-tag", "v1.0"]) == 0
    (root / "output" / "confirmatory-run-log.json").write_text(json.dumps({"dry_run": False, "partition": "confirmatory"}))
    rerun = root / "output" / "rerun.json"
    assert cli.main(["analyze", STUDY, "--partition", "confirmatory", "--commit-tag", "v1.0", "--out", str(rerun)]) == 0
    assert cli.main(["verify", STUDY, "--compare", str(rerun)]) == 0
    g3, status = _gate(repo, STUDY, "G3")
    assert g3["ok"], json.dumps(g3, indent=1)
    assert status["current"] == "G4"

    # A confirmatory generator that drifted is a red line.
    drifted = dict(record, model="example-model-2")
    llm.write_json(root / "output" / "confirmatory-generator.json", drifted)
    g3b, _ = _gate(repo, STUDY, "G3")
    assert not next(c for c in g3b["checks"] if c["id"] == "generator-drift")["ok"]
    llm.write_json(root / "output" / "confirmatory-generator.json", record)

    # A results file that breaks the schema is rejected.
    bad_results = root / "output" / "bad.json"
    bad_results.write_text(json.dumps({**json.loads(rerun.read_text()), "surprise": 1}))
    assert cli.main(["verify", STUDY, "--results", str(bad_results)]) == 1
    assert cli.main(["verify", STUDY, "--compare", str(rerun)]) == 0

    # G4: package, replay, independent attestation --------------------------
    assert cli.main(["package", STUDY]) == 0
    manifest = json.loads((root / "output" / "evidence-manifest.json").read_text())
    assert "data/rows.csv" not in manifest["files"]
    assert cli.main(["replay", STUDY, "--results", str(rerun)]) == 0
    assert cli.main(["attest", STUDY, "--results", str(rerun), "--runner-kind", "author"]) == 0
    g4a, status = _gate(repo, STUDY, "G4")
    assert not next(c for c in g4a["checks"] if c["id"] == "independent-replay")["ok"]  # the author's own replay does not count
    assert cli.main(["attest", STUDY, "--results", str(rerun), "--runner-kind", "ci", "--runner-name", "replay-attest"]) == 0
    different = root / "output" / "different.json"
    different.write_text(json.dumps({**json.loads(rerun.read_text()), "commit_tag": "def"}))
    assert cli.main(["replay", STUDY, "--results", str(different)]) == 1
    g4, status = _gate(repo, STUDY, "G4")
    assert g4["ok"], json.dumps(g4, indent=1)
    assert status["current"] == "done"
    assert len(gates.attestations(root)) == 2

    # Pressure-test: leakage audit is clean; plausibility flags a zero-spread dimension
    dims = root / "output" / "dims.json"
    dims.write_text(json.dumps({"x": {"n": 50, "sd_d": 0.0, "mean_d": 0.0, "delta": 0.1, "verdict": "equivalent"}}))
    assert cli.main(["pressure", STUDY, "--dimensions", str(dims)]) == 1
    report = json.loads((root / "output" / "pressure-report.json").read_text())
    assert next(c for c in report["checks"] if c["check"] == "leakage")["ok"]
    assert "x" in next(c for c in report["checks"] if c["check"] == "plausibility")["flags"]

    assert cli.main(["status", STUDY]) == 0
    printed = capsys.readouterr().out
    assert "current gate: done" in printed


def test_unlock_before_freeze_is_refused(workspace):
    assert cli.main(["init", STUDY, "--title", "x"]) == 0
    raw = workspace / "studies" / STUDY / "data" / "rows.csv"
    _raw_csv(raw)
    assert cli.main(["split", STUDY, "--csv", str(raw), "--id-column", "OBSID", "--seed", "1"]) == 0
    assert cli.main(["unlock", STUDY, "--reason", "too early"]) == 1


def test_freeze_after_unlock_is_refused(workspace):
    assert cli.main(["init", STUDY, "--title", "x"]) == 0
    raw = workspace / "studies" / STUDY / "data" / "rows.csv"
    _raw_csv(raw)
    assert cli.main(["split", STUDY, "--csv", str(raw), "--id-column", "OBSID", "--seed", "1"]) == 0
    assert cli.main(["unlock", STUDY, "--reason", "forced", "--force"]) == 0
    assert cli.main(["freeze", STUDY, "--version", "v1", "--allow-open"]) == 1
